name: App deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  deploy_Frontend:
    name: deploy frontend
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@main
    
        env:
          host: ${{ secrets.HNG_SERVER_HOST }}          
          username: ${{ secrets.HNG_SERVER_USERNAME }}
          password: ${{ secrets.HNG_SERVER_PASSWORD }}
          port: ${{ secrets.HNG_SERVER_PORT }}
          
        with:
          host: ${{ secrets.HNG_SERVER_HOST }}          
          username: ${{ secrets.HNG_SERVER_USERNAME }}
          password: ${{ secrets.HNG_SERVER_PASSWORD }}
          port: ${{ secrets.HNG_SERVER_PORT }}
          script: |
            cd ./applyforme-fe
            git pull
            # cd ./applyforme.web/Apply-For-Me-UI
            # npm install
            # pm2 start npm -- start
            # pm2 save
     