name: Backend Deploy

on:
  push:
    branches: [ "deployment" ]
  workflow_dispatch:

jobs:

  deploy_backend:
    name: deploy backend
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
    
        env:
          GITHUB_USERNAME: ${{ secrets.VICDAM_USER }}  
          GITHUB_TOKEN: ${{ secrets.VICDAM_TOKEN }}     
          host: ${{ secrets.HNG_SERVER_HOST }}          
          username: ${{ secrets.HNG_SERVER_USERNAME }}
          password: ${{ secrets.HNG_SERVER_PASSWORD }}
          port: ${{ secrets.HNG_SERVER_PORT }}

        with:
          host: ${{ secrets.HNG_SERVER_HOST }}          
          username: ${{ secrets.HNG_SERVER_USERNAME }}
          password: ${{ secrets.HNG_SERVER_PASSWORD }}
          port: ${{ secrets.HNG_SERVER_PORT }}
          script: |
            cd ./applyforme-be/applyforme.web
            git pull
            pm2 restart backend
            pm2 save
     