name: Applyforme

on:
  push:
    branches: [ "deployment" ]
  workflow_dispatch:
    

jobs:

  Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Apply-For-Me-UI

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install --force

    - name: Run the tests
      run: npm ci
      
    - name: Build
      run: npm run build
      
    # - name: test
    #   run: npm test

  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
    
        env:
          GITHUB_USERNAME: ${{ secrets.VICDAM_USER }}  
          GITHUB_TOKEN: ${{ secrets.VICDAM_TOKEN }}     
          host: ${{ secrets.HNG_SERVER_HOST }}          
          username: ${{ secrets.HNG_SERVER_USERNAME }}
          password: ${{ secrets.HNG_SERVER_PASSWORD }}
          port: ${{ secrets.HNG_SERVER_PORT }}

        with:
          host: ${{ secrets.HNG_SERVER_HOST }}          
          username: ${{ secrets.HNG_SERVER_USERNAME }}
          password: ${{ secrets.HNG_SERVER_PASSWORD }}
          port: ${{ secrets.HNG_SERVER_PORT }}
          script: |
            cd applyforme/applyforme.web/
            git pull
            pm2 restart backend
            cd ./Apply-For-Me-UI
            npm install
            pm2 restart frontend
            pm2 save
     